### ISSUE TITLE
Could not load file or assembly 'Fasm.NET.dll'

### ISSUE THREAD

**Issue by JackalopeGit** [Sewer56/Reloaded-Mod-Loader#16]
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Fasm.NET.dll' or one of its dependencies. The specified module could not be found.
   at Reloaded.Assembler.Assembler.FasmNETAssemble(String[] source)
   at Reloaded.Assembler.Assembler.Assemble(String[] mnemonics)
   at Reloaded_Loader.Program.Main(String[] args)
```

**Comment by Sewer56** [comment]
Install Visual C++ Redist 2012.

I have wrote my own solution that doesn't require it as dependency but it's gonna be some time till I touch Reloaded again as it's getting completely restructured and GUI rewritten in WPF.

**Comment by Sewer56** [comment]
Oh https://github.com/Sewer56/Reloaded-Mod-Loader/issues/13
Welp, that happens sometimes.

**Comment by JackalopeGit** [comment]
I am intalled Visual C++ Redist 2012.

But the issue that you are using x86 package, while I downloaded x64.

![image](https://user-images.githubusercontent.com/33356711/51430700-c34a8100-1bd3-11e9-9520-95cd9ac8801b.png)
